apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  creationTimestamp: null
  name: weaveworks-charts
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://weaveworks.github.io/weave-gitops-profile-examples/
status: {}

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-0
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.7
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m0s
  targetNamespace: cert-manager
  upgrade:
    crds: CreateReplace
  values:
    cert-manager:
      installCRDs: true
status: {}

--- 
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: policy-agent
  namespace: policy-system
spec:
  interval: 1m
  url: https://github.com/weaveworks/profiles-catalog
  ref:
    branch: 1507-gitsources

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-agent
  namespace: policy-system
  labels:
    weave.works/applied-layer: layer-1
spec:
  dependsOn:
  - name: cert-manager
    namespace: flux-system
  interval: 1m
  values:
    policy-agent:
      config:
        accountId: my-account
        clusterId: my-cluster
        audit:
          enabled: true
          sinks:
            filesystemSink:
              fileName: audit.json
        admission:
          enabled: true
          sinks:
            k8sEventsSink:
              enabled: true
            filesystemSink:
              fileName: admission.json
    policySource:
      enabled: true
      sourceName: flux-system
      path: ./policies
  chart:
    spec:
      chart: ./charts/weave-policy-agent
      sourceRef:
        kind: GitRepository
        name: policy-agent
        namespace: policy-system
      valuesFiles:
      - ./charts/weave-policy-agent/values.yaml
      interval: 1m
