apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-secret
  namespace: flux-system
spec:
  url: https://github.com/weaveworks/profiles-catalog
  ref:
    branch: 1929-eso-profile
  interval: 1m

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secret
  namespace: flux-system
  labels:
    weave.works/applied-layer: layer-0
spec:
  interval: 1m0s
  targetNamespace: external-secret
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    external-secrets:
      installCRDs: true
    secretStores:
      enabled: true
      url: ssh://git@github.com/ahsayde/ext-sercret-op
      branch: main                                  
      path: ./clusters/secrets/management                                    
      secretRef: ssh-creds                            
  chart:
    spec:
      chart: ./charts/external-secrets
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta1
        kind: GitRepository
        name: external-secrets
        namespace: flux-system
      valuesFiles:
      - ./charts/external-secrets/values.yaml
      interval: 1m
